# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bt_packet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62t_packet.proto\x12\x07moonalt\"u\n\x08RawFrame\x12\x0e\n\x06schema\x18\x01 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x04\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\x12\x14\n\x0cpixel_format\x18\x05 \x01(\t\x12\x12\n\nframe_data\x18\x06 \x01(\x0c\"v\n\tMaskFrame\x12\x0e\n\x06schema\x18\x01 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x04\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\x12\x14\n\x0cpixel_format\x18\x05 \x01(\t\x12\x12\n\nframe_data\x18\x06 \x01(\x0c\"V\n\x03\x42ox\x12\n\n\x02x1\x18\x01 \x01(\r\x12\n\n\x02y1\x18\x02 \x01(\r\x12\n\n\x02x2\x18\x03 \x01(\r\x12\n\n\x02y2\x18\x04 \x01(\r\x12\r\n\x05score\x18\x05 \x01(\x02\x12\x10\n\x08\x63lass_id\x18\x06 \x01(\x05\"j\n\nBoxesFrame\x12\x0e\n\x06schema\x18\x01 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x04\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\x12\x1b\n\x05\x62oxes\x18\x05 \x03(\x0b\x32\x0c.moonalt.Box\"\x92\x01\n\x08\x42tPacket\x12\x0e\n\x06schema\x18\x01 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x04\x12\x1e\n\x03raw\x18\x03 \x01(\x0b\x32\x11.moonalt.RawFrame\x12 \n\x04mask\x18\x04 \x01(\x0b\x32\x12.moonalt.MaskFrame\x12\"\n\x05\x62oxes\x18\x05 \x01(\x0b\x32\x13.moonalt.BoxesFrameb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bt_packet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RAWFRAME._serialized_start=28
  _RAWFRAME._serialized_end=145
  _MASKFRAME._serialized_start=147
  _MASKFRAME._serialized_end=265
  _BOX._serialized_start=267
  _BOX._serialized_end=353
  _BOXESFRAME._serialized_start=355
  _BOXESFRAME._serialized_end=461
  _BTPACKET._serialized_start=464
  _BTPACKET._serialized_end=610
# @@protoc_insertion_point(module_scope)
