# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/connection/frame_message.proto
"""Generated protocol buffer code."""

from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\x0a\x27services/connection/frame_message.proto\x12\x15golex.virtualtracking"\x83\x02\x0a\x0aInputFrame\x12\x12\x0a\x06schema\x18\x01 \x01(\x09B\x02\x18\x01\x12\x10\x0a\x08frame_id\x18\x02 \x01(\x03\x12\x11\x0a\x09timestamp\x18\x03 \x01(\x01\x12\x0d\x0a\x05width\x18\x04 \x01(\x0d\x12\x0e\x0a\x06height\x18\x05 \x01(\x0d\x12\x18\x0a\x0cpixel_format\x18\x06 \x01(\x09B\x02\x18\x01\x12\x12\x0a\x0aframe_data\x18\x07 \x01(\x0c\x122\x0a\x09schema_id\x18\x08 \x01(\x0e2\x1f.golex.virtualtracking.SchemaId\x12;\x0a\x0fpixel_format_id\x18\x09 \x01(\x0e2".golex.virtualtracking.PixelFormat*@\x0a\x08SchemaId\x12\x16\x0a\x12SCHEMA_UNSPECIFIED\x10\x00\x12\x1c\x0a\x18SCHEMA_GOLEX_VT_INPUT_V1\x10\x01*C\x0a\x0bPixelFormat\x12\x1c\x0a\x18PIXEL_FORMAT_UNSPECIFIED\x10\x00\x12\x16\x0a\x12PIXEL_FORMAT_BGR24\x10\x01b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.connection.frame_message_pb2', globals())

# @@protoc_insertion_point(module_scope)
