# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/connection/yolo_packet.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='services/connection/yolo_packet.proto',
  package='golex.virtualtracking',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n%services/connection/yolo_packet.proto\x12\x15golex.virtualtracking\"\xce\x01\n\nYoloPacket\x12\x0e\n\x06schema\x18\x01 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x03\x12\x11\n\traw_width\x18\x03 \x01(\r\x12\x12\n\nraw_height\x18\x04 \x01(\r\x12\x18\n\x10raw_pixel_format\x18\x05 \x01(\t\x12\x11\n\traw_frame\x18\x06 \x01(\x0c\x12\x12\n\nmask_width\x18\x07 \x01(\r\x12\x13\n\x0bmask_height\x18\x08 \x01(\r\x12\x12\n\nmask_frame\x18\t \x01(\x0c\x12\r\n\x05\x62oxes\x18\n \x03(\x02\x62\x06proto3'
)




_YOLOPACKET = _descriptor.Descriptor(
  name='YoloPacket',
  full_name='golex.virtualtracking.YoloPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='schema', full_name='golex.virtualtracking.YoloPacket.schema', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='golex.virtualtracking.YoloPacket.frame_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='raw_width', full_name='golex.virtualtracking.YoloPacket.raw_width', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='raw_height', full_name='golex.virtualtracking.YoloPacket.raw_height', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='raw_pixel_format', full_name='golex.virtualtracking.YoloPacket.raw_pixel_format', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='raw_frame', full_name='golex.virtualtracking.YoloPacket.raw_frame', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mask_width', full_name='golex.virtualtracking.YoloPacket.mask_width', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mask_height', full_name='golex.virtualtracking.YoloPacket.mask_height', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mask_frame', full_name='golex.virtualtracking.YoloPacket.mask_frame', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='boxes', full_name='golex.virtualtracking.YoloPacket.boxes', index=9,
      number=10, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=271,
)

DESCRIPTOR.message_types_by_name['YoloPacket'] = _YOLOPACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

YoloPacket = _reflection.GeneratedProtocolMessageType('YoloPacket', (_message.Message,), {
  'DESCRIPTOR' : _YOLOPACKET,
  '__module__' : 'services.connection.yolo_packet_pb2'
  # @@protoc_insertion_point(class_scope:golex.virtualtracking.YoloPacket)
  })
_sym_db.RegisterMessage(YoloPacket)


# @@protoc_insertion_point(module_scope)
